### ISSUE TITLE
EC2 -> 홈서버 마이그레이션

### ISSUE THREAD

**Issue by HongYeseul** [CHZZK-Study/Grass-Diary-Server#100]
- [x] 홈서버 구축
- [x] 인증서 발급
- [x] 환경변수 변경
- [x] 배포 링크 변경
- [x] 구글 로그인 API 설정 값 변경

**Comment by jjaegii** [comment]
추가사항
- [x] 홈서버 아키텍처(arm)로 빌드 스크립트 변경
- [x] 배포 스크립트 이름 변경 (deployEC2 -> deploySERVER)
- [x] 배포 브랜치 변경 (dev -> release)

**Comment by jjaegii** [comment]
인증서를 적용할 때, Spring Boot의 'application.properties' 파일에 인증서를 추가해야 하는 상황이 있습니다.
Spring Boot의 설정을 되도록 건드리지 않기 위해, Docker 컨테이너 단독 배포 대신, k3s를 사용하여 인증서 pod와 Spring 서버 pod를 분리하여 배포할 예정입니다.

**Comment by jjaegii** [comment]
인증서 적용 중, k3s LoadBalancer 서비스의 external-ip가 pending 상태인 것을 확인했습니다.
원인을 알아보니, k3s 구성 시 proxy를 설정하지 않은 것 같습니다.
금주에 추가적으로 라즈베리파이 구매를 통한 클러스터 재구성으로 다시 진행해야할 것 같습니다.
